name: Deploy Next.js to ECS

on:
  push:
    branches: [main, develop, feature/**]

jobs:
  deploy:
    name: Build and Deploy to AWS ECS
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      NEXT_PUBLIC_ENV: ${{ github.ref_name == 'main' && 'production' || 'develop' }}

    steps:
      - name: /****/ Checkout Code /****/
        uses: actions/checkout@v4

      - name: /****/ Setup Docker Buildx /****/
        uses: docker/setup-buildx-action@v3

